### ISSUE TITLE
how to  use javascript in webharvest and json

### ISSUE THREAD

**Issue by nutcrackers2** [kLeZ/WebHarvest#1]
how to  use javascript in webharvest and json

**Comment by kLeZ** [comment]
Hi, long story short: No, WebHarvest does not have a javascript engine, then it cannot execute any javascript.

WebHarvest can crawl web pages and do some declarative actions on a html string.
Executing javascript requires a javascript engine to be present inside WebHarvest, because javascript is client code and thus it must be executed client side.
Last but not least it is not by any means the purpose of WebHarvest to support a javascript engine to do client operations inside a page after it has been downloaded.
